<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKxarjud\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKxarjud/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKxarjud.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKxarjud\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKxarjud\appDevDebugProjectContainer([
    'container.build_hash' => 'Kxarjud',
    'container.build_id' => '04e7b750',
    'container.build_time' => 1552184133,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKxarjud');
