<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxr6zu0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxr6zu0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIxr6zu0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIxr6zu0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerIxr6zu0\appDevDebugProjectContainer([
    'container.build_hash' => 'Ixr6zu0',
    'container.build_id' => '27e37131',
    'container.build_time' => 1553533568,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxr6zu0');
